version: '3.3'

services:
  mysql:
    image: mysql:5.7
    container_name: vatansoft_mysql
    restart: always
    environment:
      MYSQL_DATABASE: todos
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:alpine
    container_name: vatansoft_redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data

  app:
    build: .
    environment:
      - REDIS_URL=vatansoft_redis:6379
      - DATABASE_URL=user:pass@tcp(vatansoft_mysql)/todos
    depends_on:
      - mysql
      - redis
    ports:
      - 8080:8080